[project]
name = "micondominio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "openai>=2.13.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.2.1",
]
